### ISSUE TITLE
retrieve_arbimage crashed when zoom>0

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/libdvid-cpp#39]
While it is possible that the crash was caused by some improper input from my side, I'm wondering if the function has been well tested for inputting zoom greater than 0.

Additional info from sanitizer:

==68945==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x00012b4f5800 in thread T0
    #0 0x10ea9bd9b in wrap__ZdaPv (libclang_rt.asan_osx_dynamic.dylib+0x57d9b)
    #1 0x1076e872f in lowtis::ImageService::_retrieve_image_fovea(unsigned int, unsigned int, std::__1::vector<int, std::__1::allocator<int> >, char*, int, bool, std::__1::vector<double, std::__1::allocator<double> >, std::__1::vector<double, std::__1::allocator<double> >) (liblowtis.dylib+0x1772f)
    #2 0x1076e7516 in lowtis::ImageService::retrieve_arbimage(unsigned int, unsigned int, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<double, std::__1::allocator<double> >, std::__1::vector<double, std::__1::allocator<double> >, char*, int, bool) (liblowtis.dylib+0x16516)

**Comment by tingzhao** [comment]
Moved to lowtis.
